baseURL = 'http://example.org/'
githubURL = 'https://github.com/Anthhon'
languageCode = 'en-us'
title = 'theMinimalCoder'
theme = 'my-theme'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
